services:
  app:
    build:
      context: .
      dockerfile: .docker/images/app/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_app
    networks:
      internal:
        aliases:
          - ${COMPOSE_PROJECT_NAME}-app.docker
    volumes:
      - .:/var/www
      - app_cache:/var/www/var/cache

networks:
  internal:

volumes:
  app_cache:
